[package]
name = "obdium"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.7.1"
sqlite = "0.37.0"
vin-info = "0.1.2"
chrono = "0.4.41"
regex = "1.11.1"
wildmatch = "2.4.0"
lazy_static = "1.5.0"
once_cell = "1.21.3"