use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize, Clone)]
pub struct PidInfo {
    pid: &'static str,
    mode: &'static str,
    unit: &'static str,
    pid_name: &'static str,
    formula: &'static str,
}

pub const PID_INFOS: &[PidInfo] = &[
    PidInfo { pid: "01", mode: "01", unit: "", pid_name: "Monitor status since DTCs cleared", formula: "", },
    PidInfo { pid: "02", mode: "01", unit: "", pid_name: "DTC that caused freeze frame to be stored", formula: "", },
    PidInfo { pid: "03", mode: "01", unit: "", pid_name: "Fuel system status", formula: "", },
    PidInfo { pid: "04", mode: "01", unit: "%", pid_name: "Calculated engine load", formula: "100/255 * A", },
    PidInfo { pid: "05", mode: "01", unit: "C", pid_name: "Engine coolant temperature", formula: "A - 40", },
    PidInfo { pid: "06", mode: "01", unit: "%", pid_name: "Short term fuel trim Bank 1", formula: "(100/128 * A) - 100", },
    PidInfo { pid: "07", mode: "01", unit: "%", pid_name: "Long term fuel trim Bank 1", formula: "(100/128 * A) - 100", },
    PidInfo { pid: "08", mode: "01", unit: "%", pid_name: "Short term fuel trim Bank 2", formula: "(100/128 * A) - 100", },
    PidInfo { pid: "09", mode: "01", unit: "%", pid_name: "Long term fuel trim Bank 2", formula: "(100/128 * A) - 100", },
    PidInfo { pid: "0A", mode: "01", unit: "kPa", pid_name: "Fuel pressure", formula: "3 * A", },
    PidInfo { pid: "0B", mode: "01", unit: "kPa", pid_name: "Intake manifold absolute pressure", formula: "A", },
    PidInfo { pid: "0C", mode: "01", unit: "rpm", pid_name: "Engine speed", formula: "((256 * A)+B) / 4", },
    PidInfo { pid: "0D", mode: "01", unit: "km/h", pid_name: "Vehicle speed", formula: "A", },
    PidInfo { pid: "0E", mode: "01", unit: "", pid_name: "Timing advance", formula: "A/2 - 64", },
    PidInfo { pid: "0F", mode: "01", unit: "°C", pid_name: "Intake air temperature", formula: "A - 40", },
    PidInfo { pid: "10", mode: "01", unit: "g/s", pid_name: "MAF air flow rate", formula: "((256 * A)+B) / 100", },
    PidInfo { pid: "11", mode: "01", unit: "%", pid_name: "Throttle position", formula: "100/255 * A", },
    PidInfo { pid: "12", mode: "01", unit: "", pid_name: "Commanded secondary air status", formula: "", },
    PidInfo { pid: "13", mode: "01", unit: "", pid_name: "Oxygen sensors present (in 2 banks)", formula: "", },
    PidInfo { pid: "14", mode: "01", unit: "(V, %)", pid_name: "Oxygen Sensor 1 (A: Voltage B: STFT)", formula: "V: A / 200 %: 100/128B - 100", },
    PidInfo { pid: "15", mode: "01", unit: "(V, %)", pid_name: "Oxygen Sensor 2 (A: Voltage B: STFT)", formula: "V: A / 200 %: 100/128B - 100", },
    PidInfo { pid: "16", mode: "01", unit: "(V, %)", pid_name: "Oxygen Sensor 3 (A: Voltage B: STFT)", formula: "V: A / 200 %: 100/128B - 100", },
    PidInfo { pid: "17", mode: "01", unit: "(V, %)", pid_name: "Oxygen Sensor 4 (A: Voltage B: STFT)", formula: "V: A / 200 %: 100/128B - 100", },
    PidInfo { pid: "18", mode: "01", unit: "(V, %)", pid_name: "Oxygen Sensor 5 (A: Voltage B: STFT)", formula: "V: A / 200 %: 100/128B - 100", },
    PidInfo { pid: "19", mode: "01", unit: "(V, %)", pid_name: "Oxygen Sensor 6 (A: Voltage B: STFT)", formula: "V: A / 200 %: 100/128B - 100", },
    PidInfo { pid: "1A", mode: "01", unit: "(V, %)", pid_name: "Oxygen Sensor 7 (A: Voltage B: STFT)", formula: "V: A / 200 %: 100/128B - 100", },
    PidInfo { pid: "1B", mode: "01", unit: "(V, %)", pid_name: "Oxygen Sensor 8 (A: Voltage B: STFT)", formula: "V: A / 200 %: 100/128B - 100", },
    PidInfo { pid: "1C", mode: "01", unit: "", pid_name: "OBD standards this vehicle conforms to", formula: "", },
    PidInfo { pid: "1D", mode: "01", unit: "", pid_name: "Oxygen sensors present (in 4 banks)", formula: "", },
    PidInfo { pid: "1E", mode: "01", unit: "", pid_name: "Aux input status", formula: "", },
    PidInfo { pid: "1F", mode: "01", unit: "s", pid_name: "Run time since engine start", formula: "(256 * A) + B", },
    PidInfo { pid: "21", mode: "01", unit: "km", pid_name: "Dist. with (MIL) on", formula: "(256 * A) + B", },
    PidInfo { pid: "22", mode: "01", unit: "kPa", pid_name: "Fuel Rail Pressure", formula: "0.079(256A + B)", },
    PidInfo { pid: "23", mode: "01", unit: "kPa", pid_name: "Fuel Rail Gauge Pressure", formula: "10(256A + B)", },
    PidInfo { pid: "24", mode: "01", unit: "(ratio, V)", pid_name: "Oxygen Sensor 1 (AB: AFR CD: Voltage)", formula: "(ratio: 2/65536(256A+B) V: 8/65536(256C+D)", },
    PidInfo { pid: "25", mode: "01", unit: "(ratio, V)", pid_name: "Oxygen Sensor 2 (AB: AFR CD: Voltage)", formula: "(ratio: 2/65536(256A+B) V: 8/65536(256C+D)", },
    PidInfo { pid: "26", mode: "01", unit: "(ratio, V)", pid_name: "Oxygen Sensor 3 (AB: AFR CD: Voltage)", formula: "(ratio: 2/65536(256A+B) V: 8/65536(256C+D)", },
    PidInfo { pid: "27", mode: "01", unit: "(ratio, V)", pid_name: "Oxygen Sensor 4 (AB: AFR CD: Voltage)", formula: "(ratio: 2/65536(256A+B) V: 8/65536(256C+D)", },
    PidInfo { pid: "28", mode: "01", unit: "(ratio, V)", pid_name: "Oxygen Sensor 5 (AB: AFR CD: Voltage)", formula: "(ratio: 2/65536(256A+B) V: 8/65536(256C+D)", },
    PidInfo { pid: "29", mode: "01", unit: "(ratio, V)", pid_name: "Oxygen Sensor 6 (AB: AFR CD: Voltage)", formula: "(ratio: 2/65536(256A+B) V: 8/65536(256C+D)", },
    PidInfo { pid: "2A", mode: "01", unit: "(ratio, V)", pid_name: "Oxygen Sensor 7 (AB: AFR CD: Voltage)", formula: "(ratio: 2/65536(256A+B) V: 8/65536(256C+D)", },
    PidInfo { pid: "2B", mode: "01", unit: "(ratio, V)", pid_name: "Oxygen Sensor 8 (AB: AFR CD: Voltage)", formula: "(ratio: 2/65536(256A+B) V: 8/65536(256C+D)", },
    PidInfo { pid: "2C", mode: "01", unit: "%", pid_name: "Commanded EGR", formula: "100/255 * A", },
    PidInfo { pid: "2D", mode: "01", unit: "%", pid_name: "EGR Error", formula: "(100/128 * A) - 100", },
    PidInfo { pid: "2E", mode: "01", unit: "%", pid_name: "Commanded evaporative purge", formula: "100/255 * A", },
    PidInfo { pid: "2F", mode: "01", unit: "%", pid_name: "Fuel Tank Level Input", formula: "100/255 * A", },
    PidInfo { pid: "30", mode: "01", unit: "", pid_name: "Warm-ups since codes cleared", formula: "A", },
    PidInfo { pid: "31", mode: "01", unit: "km", pid_name: "Distance traveled since codes cleared", formula: "(256 * A)+B", },
    PidInfo { pid: "32", mode: "01", unit: "Pa", pid_name: "Evap. System Vapor Pressure", formula: "((256 * A)+B) / 4", },
    PidInfo { pid: "33", mode: "01", unit: "kPa", pid_name: "Absolute Barometric Pressure", formula: "A", },
    PidInfo { pid: "34", mode: "01", unit: "(ratio, mA)", pid_name: "Oxygen Sensor 1 (AB: AFR CD: Current)", formula: "(ratio: 2/65536(256A+B) mA: ((256C + D) / 256) - 128", },
    PidInfo { pid: "35", mode: "01", unit: "(ratio, mA)", pid_name: "Oxygen Sensor 2 (AB: AFR CD: Current)", formula: "(ratio: 2/65536(256A+B) mA: ((256C + D) / 256) - 128", },
    PidInfo { pid: "36", mode: "01", unit: "(ratio, mA)", pid_name: "Oxygen Sensor 3 (AB: AFR CD: Current)", formula: "(ratio: 2/65536(256A+B) mA: ((256C + D) / 256) - 128", },
    PidInfo { pid: "37", mode: "01", unit: "(ratio, mA)", pid_name: "Oxygen Sensor 4 (AB: AFR CD: Current)", formula: "(ratio: 2/65536(256A+B) mA: ((256C + D) / 256) - 128", },
    PidInfo { pid: "38", mode: "01", unit: "(ratio, mA)", pid_name: "Oxygen Sensor 5 (AB: AFR CD: Current)", formula: "(ratio: 2/65536(256A+B) mA: ((256C + D) / 256) - 128", },
    PidInfo { pid: "39", mode: "01", unit: "(ratio, mA)", pid_name: "Oxygen Sensor 6 (AB: AFR CD: Current)", formula: "(ratio: 2/65536(256A+B) mA: ((256C + D) / 256) - 128", },
    PidInfo { pid: "3A", mode: "01", unit: "(ratio, mA)", pid_name: "Oxygen Sensor 7 (AB: AFR CD: Current)", formula: "(ratio: 2/65536(256A+B) mA: ((256C + D) / 256) - 128", },
    PidInfo { pid: "3B", mode: "01", unit: "(ratio, mA)", pid_name: "Oxygen Sensor 8 (AB: AFR CD: Current)", formula: "(ratio: 2/65536(256A+B) mA: ((256C + D) / 256) - 128", },
    PidInfo { pid: "3C", mode: "01", unit: "°C", pid_name: "Catalyst Temperature: Bank 1, Sensor 1", formula: "(((256 * A)+B) / 10) - 40", },
    PidInfo { pid: "3D", mode: "01", unit: "°C", pid_name: "Catalyst Temperature: Bank 2, Sensor 1", formula: "(((256 * A)+B) / 10) - 40", },
    PidInfo { pid: "3E", mode: "01", unit: "°C", pid_name: "Catalyst Temperature: Bank 1, Sensor 2", formula: "(((256 * A)+B) / 10) - 40", },
    PidInfo { pid: "3F", mode: "01", unit: "°C", pid_name: "Catalyst Temperature: Bank 2, Sensor 2", formula: "(((256 * A)+B) / 10) - 40", },
    PidInfo { pid: "41", mode: "01", unit: "", pid_name: "Monitor status this drive cycle", formula: "", },
    PidInfo { pid: "42", mode: "01", unit: "V", pid_name: "Control module voltage", formula: "((256 * A)+B) / 1000", },
    PidInfo { pid: "43", mode: "01", unit: "%", pid_name: "Absolute load value", formula: "(100/255) * (256A + B)", },
    PidInfo { pid: "44", mode: "01", unit: "ratio", pid_name: "Commanded Air-Fuel Equivalence Ratio", formula: "(2/65536) * (256A + B)", },
    PidInfo { pid: "45", mode: "01", unit: "%", pid_name: "Relative throttle position", formula: "100/255 * A", },
    PidInfo { pid: "46", mode: "01", unit: "°C", pid_name: "Ambient air temperature", formula: "A - 40", },
    PidInfo { pid: "47", mode: "01", unit: "%", pid_name: "Absolute throttle position B", formula: "100/255 * A", },
    PidInfo { pid: "4D", mode: "01", unit: "min", pid_name: "Time run with MIL on", formula: "256A + B", },
    PidInfo { pid: "4F", mode: "01", unit: "ratio, V, mA, kPa", pid_name: "Maximum value for AFR, oxygen sensor voltage, oxygen sensor current, and intake manifold absolute pressure", formula: "A, B, C, D * 10", },
    PidInfo { pid: "50", mode: "01", unit: "g/s", pid_name: "Maximum air flow rate from MAF sensor", formula: "A * 10", },
    PidInfo { pid: "51", mode: "01", unit: "", pid_name: "Fuel Type", formula: "", },
    PidInfo { pid: "52", mode: "01", unit: "%", pid_name: "Ethanol fuel %", formula: "100/255 * A", },
    PidInfo { pid: "53", mode: "01", unit: "kPa", pid_name: "Absolute Evap system Vapor Pressure", formula: "((256 * A)+B) / 200", },
    PidInfo { pid: "54", mode: "01", unit: "Pa", pid_name: "Evap system vapor pressure", formula: "(256 * A) + B", },
    PidInfo { pid: "55", mode: "01", unit: "%", pid_name: "Short term secondary oxygen sensor trim, A: bank 1, B: bank 3", formula: "", },
    PidInfo { pid: "59", mode: "01", unit: "kPa", pid_name: "Fuel rail absolute pressure", formula: "10(256A + B)", },
    PidInfo { pid: "5A", mode: "01", unit: "%", pid_name: "Relative accelerator pedal position", formula: "100/255 * A", },
    PidInfo { pid: "5B", mode: "01", unit: "%", pid_name: "Hybrid battery pack remaining life", formula: "100/255 * A", },
    PidInfo { pid: "5C", mode: "01", unit: "°C", pid_name: "Engine oil temperature", formula: "A - 40", },
    PidInfo { pid: "5D", mode: "01", unit: "°", pid_name: "Fuel injection timing", formula: "(((256 * A)+B) / 128) - 210", },
    PidInfo { pid: "5E", mode: "01", unit: "L/h", pid_name: "Engine fuel rate", formula: "((256 * A)+B) / 20", },
    PidInfo { pid: "5F", mode: "01", unit: "", pid_name: "Emission requirements to which vehicle is designed", formula: "", },
    PidInfo { pid: "61", mode: "01", unit: "%", pid_name: "Driver's demand engine - percent torque", formula: "A - 125", },
    PidInfo { pid: "62", mode: "01", unit: "%", pid_name: "Actual engine - percent torque", formula: "A - 125", },
    PidInfo { pid: "63", mode: "01", unit: "Nm", pid_name: "Engine reference torque", formula: "256A + B", },
    PidInfo { pid: "64", mode: "01", unit: "%", pid_name: "Engine percent torque data", formula: "Subtract 125 from A - E", },
    PidInfo { pid: "65", mode: "01", unit: "", pid_name: "Auxiliary input / output supported", formula: "", },
    PidInfo { pid: "66", mode: "01", unit: "g/s", pid_name: "Mass air flow sensor", formula: "{A0}== Sensor A Supported", },
    PidInfo { pid: "67", mode: "01", unit: "°C", pid_name: "Engine coolant temperature", formula: "{A0}== Sensor 1 Supported", },
    PidInfo { pid: "68", mode: "01", unit: "°C", pid_name: "Intake air temperature sensor", formula: "{A0}== Sensor 1 Supported", },
    PidInfo { pid: "69", mode: "01", unit: "", pid_name: "Actual EGR, Commanded EGR, and EGR Error", formula: "", },
    PidInfo { pid: "6A", mode: "01", unit: "", pid_name: "Commanded Diesel intake air flow control and relative intake air flow position", formula: "", },
    PidInfo { pid: "6B", mode: "01", unit: "", pid_name: "Exhaust gas recirculation temperature", formula: "", },
    PidInfo { pid: "6C", mode: "01", unit: "", pid_name: "Commanded throttle actuator control and relative throttle position", formula: "", },
    PidInfo { pid: "6D", mode: "01", unit: "", pid_name: "Fuel pressure control system", formula: "", },
    PidInfo { pid: "6E", mode: "01", unit: "", pid_name: "Injection pressure control system", formula: "", },
    PidInfo { pid: "6F", mode: "01", unit: "", pid_name: "Turbocharger compressor inlet pressure", formula: "", },
    PidInfo { pid: "70", mode: "01", unit: "", pid_name: "Boost pressure control", formula: "", },
    PidInfo { pid: "71", mode: "01", unit: "", pid_name: "Variable Geometry turbo (VGT) control", formula: "", },
    PidInfo { pid: "72", mode: "01", unit: "", pid_name: "Wastegate control", formula: "", },
    PidInfo { pid: "73", mode: "01", unit: "", pid_name: "Exhaust pressure", formula: "", },
    PidInfo { pid: "74", mode: "01", unit: "RPM", pid_name: "Turbocharger RPM", formula: "", },
    PidInfo { pid: "75", mode: "01", unit: "°C", pid_name: "Turbocharger temperature", formula: "", },
    PidInfo { pid: "76", mode: "01", unit: "°C", pid_name: "Turbocharger temperature", formula: "", },
    PidInfo { pid: "77", mode: "01", unit: "°C", pid_name: "Charge air cooler temperature (CACT)", formula: "", },
    PidInfo { pid: "78", mode: "01", unit: "°C", pid_name: "Exhaust Gas temperature (EGT) Bank 1", formula: "", },
    PidInfo { pid: "79", mode: "01", unit: "°C", pid_name: "Exhaust Gas temperature (EGT) Bank 2", formula: "", },
    PidInfo { pid: "7A", mode: "01", unit: "", pid_name: "Diesel particulate filter (DPF)", formula: "", },
    PidInfo { pid: "7B", mode: "01", unit: "", pid_name: "Diesel particulate filter (DPF)", formula: "", },
    PidInfo { pid: "7C", mode: "01", unit: "°C", pid_name: "Diesel Particulate filter (DPF) temperature", formula: "(((256 * A)+B) / 10) - 40", },
    PidInfo { pid: "7D", mode: "01", unit: "", pid_name: "NOx NTE", formula: "", },
    PidInfo { pid: "7E", mode: "01", unit: "", pid_name: "PM NTE", formula: "", },
    PidInfo { pid: "7F", mode: "01", unit: "s", pid_name: "Engine run time", formula: "B(2^24) + C(2^16) + D(2^8) + E", },
    PidInfo { pid: "81", mode: "01", unit: "", pid_name: "Engine run time for Auxiliary Emissions Control Device(AECD)", formula: "", },
    PidInfo { pid: "82", mode: "01", unit: "", pid_name: "Engine run time for Auxiliary Emissions Control Device(AECD)", formula: "", },
    PidInfo { pid: "83", mode: "01", unit: "", pid_name: "NOx sensor", formula: "", },
    PidInfo { pid: "84", mode: "01", unit: "", pid_name: "Manifold surface temperature", formula: "", },
    PidInfo { pid: "85", mode: "01", unit: "%", pid_name: "NOx reagent system", formula: "100/255 * F", },
    PidInfo { pid: "86", mode: "01", unit: "", pid_name: "Particulate matter (PM) sensor", formula: "", },
    PidInfo { pid: "87", mode: "01", unit: "kPa", pid_name: "Intake manifold absolute pressure", formula: "", },
    PidInfo { pid: "88", mode: "01", unit: "", pid_name: "SCR Induce System", formula: "", },
    PidInfo { pid: "89", mode: "01", unit: "", pid_name: "Run Time for AECD #11-#15", formula: "", },
    PidInfo { pid: "8A", mode: "01", unit: "", pid_name: "Run Time for AECD #16-#20", formula: "", },
    PidInfo { pid: "8B", mode: "01", unit: "", pid_name: "Diesel Aftertreatment", formula: "", },
    PidInfo { pid: "8C", mode: "01", unit: "", pid_name: "O2 Sensor (Wide Range)", formula: "", },
    PidInfo { pid: "8D", mode: "01", unit: "%", pid_name: "Throttle Position G", formula: "", },
    PidInfo { pid: "8E", mode: "01", unit: "%", pid_name: "Engine Friction - Percent Torque", formula: "A - 125", },
    PidInfo { pid: "8F", mode: "01", unit: "", pid_name: "PM Sensor Bank 1 & 2", formula: "", },
    PidInfo { pid: "90", mode: "01", unit: "h", pid_name: "WWH-OBD Vehicle OBD System Information", formula: "", },
    PidInfo { pid: "91", mode: "01", unit: "h", pid_name: "WWH-OBD Vehicle OBD System Information", formula: "", },
    PidInfo { pid: "92", mode: "01", unit: "", pid_name: "Fuel System Control", formula: "", },
    PidInfo { pid: "93", mode: "01", unit: "h", pid_name: "WWH-OBD Vehicle OBD Counters support", formula: "", },
    PidInfo { pid: "94", mode: "01", unit: "", pid_name: "NOx Warning And Inducement System", formula: "", },
    PidInfo { pid: "98", mode: "01", unit: "°C", pid_name: "Exhaust Gas Temperature Sensor", formula: "", },
    PidInfo { pid: "99", mode: "01", unit: "°C", pid_name: "Exhaust Gas Temperature Sensor", formula: "", },
    PidInfo { pid: "9A", mode: "01", unit: "", pid_name: "Hybrid/EV Vehicle System Data, Battery, Voltage", formula: "", },
    PidInfo { pid: "9B", mode: "01", unit: "%", pid_name: "Diesel Exhaust Fluid Sensor Data", formula: "100/255 * D", },
    PidInfo { pid: "9C", mode: "01", unit: "", pid_name: "O2 Sensor Data", formula: "", },
    PidInfo { pid: "9D", mode: "01", unit: "g/s", pid_name: "Engine Fuel Rate", formula: "", },
    PidInfo { pid: "9E", mode: "01", unit: "kg/h", pid_name: "Engine Exhaust Flow Rate", formula: "", },
    PidInfo { pid: "9F", mode: "01", unit: "", pid_name: "Fuel System Percentage Use", formula: "", },
    PidInfo { pid: "A1", mode: "01", unit: "ppm", pid_name: "NOx Sensor Corrected Data", formula: "", },
    PidInfo { pid: "A2", mode: "01", unit: "mg/stroke", pid_name: "Cylinder Fuel Rate", formula: "((256 * A)+B) / 32", },
    PidInfo { pid: "A3", mode: "01", unit: "Pa", pid_name: "Evap System Vapor Pressure", formula: "", },
    PidInfo { pid: "A4", mode: "01", unit: "ratio", pid_name: "Transmission Actual Gear", formula: "((256 * C) + D) / 1000", },
    PidInfo { pid: "A5", mode: "01", unit: "%", pid_name: "Commanded Diesel Exhaust Fluid Dosing", formula: "B / 2", },
    PidInfo { pid: "A6", mode: "01", unit: "", pid_name: "Odometer", formula: "(A(2^24) + B(2^16) + C(2^8) + D) / 10", },
    PidInfo { pid: "A7", mode: "01", unit: "", pid_name: "NOx Sensor Concentration Sensors 3 and 4", formula: "", },
    PidInfo { pid: "A8", mode: "01", unit: "", pid_name: "NOx Sensor Corrected Concentration Sensors 3 and 4", formula: "", },
    PidInfo { pid: "A9", mode: "01", unit: "", pid_name: "ABS Disable Switch State", formula: "{A0}= 1:Supported; 0:Unsupported", },
    PidInfo { pid: "C3", mode: "01", unit: "%", pid_name: "Fuel Level Input A/B", formula: "", },
    PidInfo { pid: "C4", mode: "01", unit: "seconds / Count", pid_name: "Exhaust Particulate Control System Diagnostic Time/Count", formula: "", },
    PidInfo { pid: "C5", mode: "01", unit: "kPa", pid_name: "Fuel Pressure A and B", formula: "", },
    PidInfo { pid: "C7", mode: "01", unit: "km", pid_name: "Distance Since Reflash or Module Replacement", formula: "", },
];
