/// A file containing an enum
/// that include a list of commonly used ElementIds.
///
/// These element id's are from the Element table
/// located in the NHTSA local database and used
/// to retrieve specific information about an ELEMENT
/// from the Patterns table alongside a key and VinSchemaId.

#[derive(Copy, Clone)]
pub enum ElementId {
    EngineModel = 18,
    EngineManufacturer = 146,
    EngineDisplacement = 13,
    EngineCylinderCount = 9,
    ValveTrainDesign = 62,
    HasTurbo = 135,
    FuelType = 24,
    FuelDeliveryType = 67,

    VehicleDoorCount = 14,
    VehicleModel = 28,

    ManufacturerCountry = 8,
    PlantCity = 31,
    PlantCountry = 75,
    NumberOfSeats = 33,
    Windows = 40,
    BodyClass = 5,
    DriveType = 15,
    // BatteryType = 2
    // BedType = 3,
    // BodyCab = 4,
    // BodyStyle = 5,
    // DestinationMarket = 10,
    // DriveType = 15,
    // EntertainmentSystem = 23,
    // FuelType = 24,
    // GrossVehicleWeightRating = 25,
    // Make = 26,
    // Manufacturer = 27,
    // Model = 28,
    // Steering = 36,
    // Transmission = 37,
    // VehicleType = 39,
    // BrakeSystem = 42,
    // AirBagLocations = 55,
    // AirBagLocations = 56,
    // WheelBaseType = 60,
    // ValvetrainDesign = 62,
    // EngineConfiguration = 64,
    // AirBagLocFront = 65,
    // FuelType = 66,
    // FuelDeliveryType = 67,
    // AirBagLocKnee = 69,
    // EVDriveUnit = 72,
    // Country = 75,
    // Pretensioner = 78,
    // SeatBeltsAll = 79,
    // AdaptiveCruiseControl = 81,
    // ABS = 86,
    // AutoBrake = 87,
    // BlindSpotMonitoring = 88,
    // vNCSABodyType = 96,
    // vNCSAMake = 97,
    // vNCSAModel = 98,
    // ECS = 99,
    // TractionControl = 100,
    // ForwardCollisionWarning = 101,
    // LaneDepartureWarning = 102,
    // LaneKeepSystem = 103,
    // RearVisibilityCamera = 104,
    // ParkAssist = 105,
    // AirBagLocations = 107,
    // TrailerType = 116,
    // TrailerBodyType = 117,
    // CoolingType = 122,
    // ElectrificationLevel = 126,
    // ChargerLevel = 127,
    // Turbo = 135,
    // ErrorCode = 143,
    // AxleConfiguration = 145,
    // BusFloorConfigType = 148,
    // BusType = 149,
    // CustomMotorcycleType = 151,
    // MotorcycleSuspensionType = 152,
    // MotorcycleChassisType = 153,
    // TPMS = 168,
    // DynamicBrakeSupport = 170,
    // PedestrianAutomaticEmergencyBraking = 171,
    // AutoReverseSystem = 172,
    // AutomaticPedestrainAlertingSound = 173,
    // CAN_AACN = 174,
    // EDR = 175,
    // KeylessIgnition = 176,
    // DaytimeRunningLight = 177,
    // LowerBeamHeadlampLightSource = 178,
    // SemiautomaticHeadlampBeamSwitching = 179,
    // AdaptiveDrivingBeam = 180,
    // RearCrossTrafficAlert = 183,
    // GrossVehicleWeightRating = 184,
    // GrossVehicleWeightRating = 185,
    // GrossVehicleWeightRating = 190,
    // RearAutomaticEmergencyBraking = 192,
    // BlindSpotIntervention = 193,
    // LaneCenteringAssistance = 194,
    // NonLandUse = 195,
    // FuelTankType = 200,
    // FuelTankMaterial = 201,
    // CombinedBrakingSystem = 202,
    // WheelieMitigation = 203,
}

impl ElementId {
    pub fn as_i64(&self) -> i64 {
        *self as i64
    }
}
