name: Rust

on:
  push:
    branches: [ "main", "vin" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Download and move VPIC database
      run: |
        curl -L -o data/vpic.sqlite "https://www.dropbox.com/scl/fi/qt21pwczi1pyv7syh05cy/vpic.sqlite?rlkey=zk0qh8q1mn6wyrjm8njfn61r0&e=1&st=ef0qnpt8&dl=1"
    - name: Build
      run: cargo build
    - name: Tests
      run: cargo test
    - name: Generate Docs
      run: cargo doc --no-deps
    - name: Format
      run: cargo fmt
    - name: Clippy
      run: cargo clippy -- -D warnings
