name: Rust

on:
  push:
    branches: [ "main", "vin" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install Git LFS
      run: git lfs install
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Build
      run: cargo build
    - name: Tests
      run: cargo test
    - name: Generate Docs
      run: cargo doc --no-deps
    - name: Format
      run: cargo fmt
    - name: Clippy
      run: cargo clippy
